### ISSUE TITLE
Add photos to profiles

### ISSUE THREAD

**Issue by makinde** [devcolor/majorkey#16]
could be loaded from Fb or LinkedIn

**Comment by makinde** [comment]
Looked into this a bit. Seems possible via https://www.avatars.io/ . 21 people have facebook links in major key, so we could get pics from there. We might also have decent coverage using gravatar with emails as well. Seems like a decent stopgap. pull the photo from elsewhere and ask people to upload a photo there.

**Comment by astonm** [comment]
Or [Gravatar](https://en.gravatar.com/), which I think Github uses.

**Comment by makinde** [comment]
Yeah, gravatar is the way to go. github and Slack use it as well, so it's perfect.
