### ISSUE TITLE
[Duplicate] Add ability to group directory by Squad

### ISSUE THREAD

**Issue by makinde** [devcolor/majorkey#3]
I imagine this can be implemented as a post query step. After you get all the data for members, group stuff into subdicts based on a query flag. Default could be that there's just one group that everyone is in so display is always simple. It would look something like this:

SF1
-----
[profile] [profile]

SF2
-----
[profile] [profile]

**Comment by astonm** [comment]
Is the idea to allow this as a sorting step on the directory page, or do you want to always show the directory split by squad?

**Comment by makinde** [comment]
To make it an option. I imagine having a collection of filters at the top
of the directory that allows it to be sorted, grouped, filtered...

I think the most basic way to do this would be to have the template support
rendering results in arbitrary groups with titles. Then we can add query
param to group by Squad.
