### ISSUE TITLE
Home and work location should be a dropdown on edit page

### ISSUE THREAD

**Issue by makinde** [devcolor/majorkey#5]
That way it is more conical and easier to filter on. This is a simple-ish front end change, and should give us time to figure out a longer term solution

**Comment by astonm** [comment]
We use https://github.com/caolan/forms and have some custom code in https://github.com/devcolor/majorkey/blob/master/forms.js to produce HTML form elements that are styled like Bootstrap. We should probably make a new `type` that is `select` that returns a `fields.string` with a `widgets.select` as its widget, with the `choices` for the widget passed in to `bootstrapField` in the `options` object.
