### ISSUE TITLE
Squad meeting edit doesn't pre-load everything

### ISSUE THREAD

**Issue by astonm** [devcolor/majorkey#57]
It looks like when you click "edit meeting" it correctly loads the date, location and presenter. It gets the start and end time wrong, though, and also the food option is not set.

**Comment by makinde** [comment]
- [ ] Food not set, yep, I see the fix
- [ ] Can you screenshot or point out the specific case where the time isn't set correctly? Not easily seeing the time issue in dev.

**Comment by makinde** [comment]
Also, which browser are you using?

**Comment by astonm** [comment]
I'm in Chrome. Here's a screenshot from "My Squad"

<img width="467" alt="screenshot 2016-04-27 16 33 08" src="https://cloud.githubusercontent.com/assets/1728824/14871302/d30cd8fe-0c95-11e6-9add-d9ba01943ffb.png">

And here's what I see once I click to edit the meeting.

<img width="955" alt="screenshot 2016-04-27 16 33 15" src="https://cloud.githubusercontent.com/assets/1728824/14871304/d5e085e4-0c95-11e6-9b95-6690897210f6.png">

**Comment by makinde** [comment]
Whoops, the dropdown, right?
